### ISSUE TITLE
 java.util.ConcurrentModificationException:, even when using stately's concurrent classes 👀 

### ISSUE THREAD

**Issue by Shabinder** [touchlab/Stately#105]
```
Exception java.util.ConcurrentModificationException:
  at java.util.ArrayList$Itr.next (ArrayList.java:860)
  at co.touchlab.stately.collections.ConcurrentMutableIterator$next$1.invoke (ConcurrentMutableIterator.java:11)
  at co.touchlab.stately.collections.ConcurrentMutableIterator.next (ConcurrentMutableIterator.java:16)
  at arrow.core.IterableKt.flatten (Iterable.kt)
  at in.shabinder.shared.provider.query.DefaultQueryResolver$getRelatedSongs$2$invokeSuspend$$inlined$buildParMergedIorNelSafely$1$1.invokeSuspend (DefaultQueryResolver.java:165)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:12)
  at kotlinx.coroutines.DispatchedTask.run
  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run (LimitedDispatcher.java:4)
  at kotlinx.coroutines.scheduling.TaskImpl.run
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely (CoroutineScheduler.java:1)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask (CoroutineScheduler.java:63)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker (CoroutineScheduler.java:63)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run (CoroutineScheduler.java:63)
```

**Comment by Shabinder** [comment]
```
Fatal Exception: java.util.ConcurrentModificationException:
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at co.touchlab.stately.collections.ConcurrentMutableIterator$next$1.invoke(ConcurrentMutableIterator.java:11)
       at co.touchlab.stately.collections.ConcurrentMutableIterator.next(ConcurrentMutableIterator.java:16)
       at kotlinx.collections.immutable.implementations.immutableList.PersistentVectorBuilder.copyToBuffer(PersistentVectorBuilder.java:12)
       at kotlinx.collections.immutable.implementations.immutableList.PersistentVectorBuilder.addAll(PersistentVectorBuilder.java:11)
       at kotlinx.collections.immutable.implementations.immutableList.SmallPersistentVector.addAll(SmallPersistentVector.java:17)
       at kotlinx.collections.immutable.ExtensionsKt.plus(Extensions.kt:5)
       at kotlinx.collections.immutable.ExtensionsKt.toPersistentList(Extensions.kt:4)
       at kotlinx.collections.immutable.ExtensionsKt.toImmutableList(Extensions.kt:2)
       at in.shabinder.shared.screens.home.discover.search.store.SoundBoundSearchStoreFactory$ExecutorImpl$search$processEmission$1.invokeSuspend(SoundBoundSearchStoreFactory.java:69)
       at in.shabinder.shared.screens.home.discover.search.store.SoundBoundSearchStoreFactory$ExecutorImpl$search$processEmission$1.invoke(SoundBoundSearchStoreFactory.java:21)
       at in.shabinder.shared.screens.home.discover.search.store.SoundBoundSearchStoreFactory$ExecutorImpl$search$processEmission$1.invoke(SoundBoundSearchStoreFactory.java:21)
       
```

**Comment by kpgalligan** [comment]
Any more context here? Version, what it's doing, etc?

**Comment by Shabinder** [comment]
Version: 
statelyVersion = "2.0.0-rc1"
statelyIsoVersion = "2.0.0-rc1"

ConcurrentMutableList -> ImmultableList  
fun <T> Iterable<T>.toImmutableList(): ImmutableList<T> =
        this as? ImmutableList
        ?: this.toPersistentList()

from kotlinx.collections.immutable

**Comment by Shabinder** [comment]
lmk if anything more is needed form my end

**Comment by kpgalligan** [comment]
It shouldn't make a difference to the issue, but I would bump up the Stately version when you get a chance. `2.0.5` is the latest.

**Comment by Shabinder** [comment]
Yeah, will do, but wont resolve this issue I believe as u said as well.
How would it be possible, ConcurrentMutableList synchronised isnt working/holding up as one would expect ?

to note: all traces are coming from **ConcurrentMutableIterator.next()**

**Comment by Shabinder** [comment]
Because the synchronisation lock is always applied on new instance of ArrayList Iterator, r8?
<img width="308" alt="image" src="https://github.com/touchlab/Stately/assets/44765050/18a9f621-614f-48a0-9589-3ce5f8c2c1e8">

instead shouldn't we use the list itself as a synchronizable lock?

If this is the case, lmk, happy to open an MR.

**Comment by kpgalligan** [comment]
OK, poking around for a bit now. See how it goes...

**Comment by kpgalligan** [comment]
Just ran this:

```kotlin
class MiscTest {
    @Test
    fun testImmutableConversion(){
        val l = ConcurrentMutableList<SomeData>()
        repeat(20){l.add(SomeData("arst $it"))}
        val il = l.toImmutableList()
        println(il)
    }
}

data class SomeData(val s: String)
```

That works. Will dig through your comments in more detail to see if I can find a good repro.

**Comment by Shabinder** [comment]
Above Snippet is not concurrent right 👀 and being accessed and modifed across multiple threads 👀

**Comment by kpgalligan** [comment]
I actually thought about it after sending this. The problem isn't complicated. Rather obvious looking at it now. I'll have to look at the iterator contract here and think through this a bit.

**Comment by kpgalligan** [comment]
This fails, no concurrency needed. Just changing the underlying list.

```kotlin
    fun testImmutableConversion(){
        val l = ConcurrentMutableList<SomeData>()
        repeat(20){l.add(SomeData("arst $it"))}
        val iter = l.iterator()
        iter.next()
        l.add(SomeData("Hello"))
        iter.next()
        val il = l.toImmutableList()
        println(il)
    }
```
The "simple" answer would be to copy the list and return an iterator to that. Obviously, that means making a whole new list, which isn't great. Also, the returned iterator should be a `MutableIterator`, and changing values to it wouldn't impact the original list, which is bad. In theory, the "proper" implementation would handle underlying changes and handle changes applied to the iterator.

**Comment by kpgalligan** [comment]
The function above works for iOS, but not JVM (in a single-threaded context only). The plot thickens.

**Comment by Shabinder** [comment]
> copy the list and return an iterator to that.

In some of my use-cases, above is a deal-breaker since list is too extensive and copying will hurt performance, since same operation runs multiple times in some scenarios.

**Comment by Shabinder** [comment]
putting a synchronised lock on list rather than iterator in below shown method would be the simple solution I believe, will have to test, but not at console as of now.
https://github.com/touchlab/Stately/issues/105#issuecomment-1825908139

**Comment by kpgalligan** [comment]
> putting a synchronised lock on list rather than iterator in below shown method would be the simple solution I believe, will have to test, but not at console as of now.

Not sure what you mean about that. Example code would be good. The issue in my sample code is that any change to the underlying list will "break" the iterator, even in the same thread, so the synchronization doesn't matter. That's JVM-only. On iOS, changes to the underlying list *don't* break the iterator. For your case, the "simple" solution would be to provide a synchronized method that takes a lambda block, which would allow the creation of the immutable list to happen atomically. Creating and holding onto an iterator, where the delegate may change after the iterator is created, is where this goes off the rails (again, JVM only, although I'm not sure how the native implementations interpret changes to the underlying collection).

**Comment by FunkyMuse** [comment]
One famous lib is using stately under the hood, so the issue is apparent that it indeed happens on JVM only, can reproduce it on Android and Desktop but not on iOS

https://github.com/Kamel-Media/Kamel/issues/75

**Comment by luca992** [comment]
@kpgalligan yeah I recently tried fixing concurrent modification exceptions for kamel by moving from `LinkedHashMap` to stately's `ConcurrentMutableMap`. https://github.com/Kamel-Media/Kamel/pull/76/files

As @FunkyMuse pointed out some people are still experiencing `ConcurrentModificationException`. Is there more to using `ConcurrentMutableMap` correctly than just swapping out use of `LinkedHashMap`?

**Comment by DRSchlaubi** [comment]
We fixed this issue by using the JDK ConcurrentHashMap on JVM, however a fix would be great either way

**Comment by lukellmann** [comment]
https://github.com/touchlab/Stately/issues/112 is also related

**Comment by lukellmann** [comment]
> We fixed this issue by using the JDK ConcurrentHashMap on JVM, however a fix would be great either way

Yeah, a fix would definitely be needed for other platforms.

**Comment by ben-gooding-sky** [comment]
This is still an issue for both`ConcurrentMutableMap` and `ConcurrentMutableList`, only when you try iterating over them

This test verifies it 
```
        val concurrentMap = ConcurrentMutableMap<String, String>()
        concurrentMap["test"] = "value"
        concurrentMap["test2"] = "value"
        val iterator = concurrentMap.iterator()
        var count = 0
        while (iterator.hasNext()) {
            count++
            concurrentMap["test3"] = "value"
            val next = iterator.next()
            assertNotNull(next)
        }
        assertEquals(3, count)
```

^^ exception is thrown

If you use KTor `ConcurrentMap` which can use all the same functionality as above, it works fine

**Comment by kpgalligan** [comment]
This part of the library needs some attention. Honestly, I had assumed there would be better KMP options popping up, so the implementations were fairly simple. Wrapping mutable collections with synchronize/mutex. The eventual intention was to deprecate this if a much better one emerged (or maybe wrap/delegate to the "better" implementation).

With that specifically, I'd need to dig into how iterator is created. After a quick look, `iterator()` ultimately calls `entries.iterator()`. The stdlib implementation may do so in a way that uses the underlying non-guarded implementation vs the wrapped one.

**Comment by luca992** [comment]
https://youtrack.jetbrains.com/issue/KT-62423

could this help? It's on the [new roadmap](https://kotlinlang.org/docs/roadmap.html)
